"""Create DB

Revision ID: ea96100ecb5f
Revises: 
Create Date: 2023-03-28 13:12:43.843434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea96100ecb5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('odds', sa.Integer(), nullable=True),
    sa.Column('wager', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.id'], name=op.f('fk_user_bets_bet_id_bets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_bets_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_bets')
    op.drop_table('users')
    op.drop_table('bets')
    # ### end Alembic commands ###
