"""Deleted join table

Revision ID: f628b02e85ac
Revises: ea96100ecb5f
Create Date: 2023-03-28 14:12:15.340498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f628b02e85ac'
down_revision = 'ea96100ecb5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_bets')
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_bets_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bets_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('user_bets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('bet_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.id'], name='fk_user_bets_bet_id_bets'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_bets_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
